version: "3"

services:
  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - 81:81
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/mini.conf
    depends_on:
      - userservice
      - statusservice
      - storyservice

  userservice:
    build: ./back-end
    restart: unless-stopped
    depends_on:
      - userdb

  userdb:
    image: mongo

    ports:
      - 5000:5000

    restart: unless-stopped
    volumes:
      - /mongo:/data/db

  statusservice:
    build: ./Thoughts/back-end
    restart: unless-stopped
    depends_on:
      - statusdb

  statusdb:
    image: mongo

    ports:
      - 5002:5002

    restart: unless-stopped

  storyservice:
    build: ./Stories/back-end
    restart: unless-stopped
    depends_on:
      - storydb
      - storyobjectdb

  storydb:
    image: mongo

    ports:
      - 5001:5001

    restart: unless-stopped

  storyobjectdb:
    image: minio/minio:latest
    environment:
      - MINIO_ACCESS_KEY=GoRpyjZTJLzsFVlF
      - MINIO_SECRET_KEY=Q9b06VKOrffbrmm2d8ZlK6XKvEfpxKm8
    command: server --address 0.0.0.0:9000 /data
